### ISSUE TITLE
moving to ropensci

### ISSUE THREAD

**Issue by sckott** [ropensci/rseaaroundus#8]
hi - scott here from ropensci - I think we can move in one of two ways - you could make me an admin here and I can move or i can put one of you on a team with admin within ropensci, thoughts?

**Comment by EvilScott** [comment]
@vkirkl can you handle this?

**Comment by vkirkl** [comment]
@sckott , I've added you as an admin here ... you should be all set.
@Dengaloo ... we should probably clean up the org users list as some point soon  ... lots of Vulcan folks, in particular, that can be removed :)

**Comment by sckott** [comment]
cool, moved over - can remove me from seaaroundus now
